### ISSUE TITLE
Trim canvas sizes and make icons square

### ISSUE THREAD

**Issue by o-l-a-v** [David-Summers/Azure-Design#53]
In addition to issue/ feature request #52, I'd like to request that canvas sizes/ empty space/ padding is shaved off, but also keep the icons (or canvas rather, thus the icon file as a whole), square.

* Example: If an icon is 20 high and 15 wide, but the actual graphics if empty canvas is shaved off is 12x10, make sure the icon/ canvas size ends up 12x12

### Example use case

* Draw.io/ Diagrams anchors width to height, so rectangular icons ends up with wrong dimensions when resized.

### Manual workaround for now

* Use Inkscape to shrink canvas ( CTRL + SHIFT + R), adjust "Front page" dimension to be square ( CTRL + SHIFT + D ) if neccessary.

**Comment by David-Summers** [comment]
Hi Olav, this should be fixed now in version 4.3 which just released. Was fun to do, as the current versions of inkscape do not process verbs, so doing something like "--verb=FitCanvasToDrawing --verb=FileSave --verb=FileQuit" as a batch process did nothing. Figured out a work around though.

**Comment by o-l-a-v** [comment]
`Network Security Group.svg` in v4.3 does not have added padding to make it look correct, ratio wise, while dimensions are 1:1. So this is not solved yet?

Made a new issue: #54 

But maybe I just should've commented on this one.
